### ISSUE TITLE
Question regarding Eq.(4)

### ISSUE THREAD

**Issue by danelee2601** [magic-research/vector_quantization#2]
C(z) refers to the quantized latent vectors.
x^T refers to the feature map obtained with a pretrained teacher.

According to Fig. 3(c), the quantized latent vectors are learned by minimizing the gap to the feature map, x^T. However, the Eq. (4) suggests minimization between a reconstructed image, denoted by D(C(z)), and the feature map. This part puzzles me.

Am I mistaken in my understanding?

Thanks for your answer in advance!

**Comment by LutingWang** [comment]
Apologies for the ambiguity. The symbol $D$ in Eq. (4) should have been $D'$ or $\sigma$. Both VQGAN and VQ-KD are implemented as autoencoders in the released code. Specifically, the decoder in VQGAN reconstructs the image, while the decoder in VQ-KD reconstructs an IU feature. Therefore, VQ-KD decoder functions as a feature adaptor, a common component in knowledge distillation (usually denoted as $\sigma$). Note that Fig. 3(c) omits this module to focus on the impact of IU models on the tokenizer.
